"""adicion de tabla historial de precios 3 

Revision ID: 5bbf83bb1c3d
Revises: a16bb98bad2c
Create Date: 2024-05-25 13:05:39.641279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbf83bb1c3d'
down_revision = 'a16bb98bad2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_precios_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_historial_precio', sa.Integer(), nullable=False))
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_precios_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id_historial_precio')

    # ### end Alembic commands ###
