"""Correcciones en modelo y rutas para Cliente 4 

Revision ID: 8f29943e9592
Revises: d6e7ea98c365
Create Date: 2024-05-25 11:05:05.446065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f29943e9592'
down_revision = 'd6e7ea98c365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('id_cliente')

    # ### end Alembic commands ###
