"""Correcciones en modelo y rutas para Cliente

Revision ID: d6e7ea98c365
Revises: 
Create Date: 2024-05-25 10:47:51.376184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e7ea98c365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.drop_column('seleccionar_producto')
        batch_op.drop_column('solicitar_producto')
        batch_op.drop_column('recibir_producto')
        batch_op.drop_column('reclamar_producto')
        batch_op.drop_column('id_cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cliente', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('reclamar_producto', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recibir_producto', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('solicitar_producto', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seleccionar_producto', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('nombre')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
