"""roles

Revision ID: dcb414a7f89e
Revises: 5b9eae7a3f6e
Create Date: 2024-05-25 15:54:21.077583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb414a7f89e'
down_revision = '5b9eae7a3f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webpay')
    op.drop_table('bodeguero')
    op.drop_table('ferramax')
    op.drop_table('contador')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'rol_cliente', ['rol_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rol_id')
        batch_op.drop_column('password_hash')

    op.create_table('contador',
    sa.Column('id_contador', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('registrar_entrega', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('registrar_pago', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_contador', name='contador_pkey')
    )
    op.create_table('ferramax',
    sa.Column('id_ferramax', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_ferramax', name='ferramax_pkey')
    )
    op.create_table('bodeguero',
    sa.Column('id_bodeguero', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('preparar_productos', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('entregar_pedidos', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_bodeguero', name='bodeguero_pkey')
    )
    op.create_table('webpay',
    sa.Column('id_webpay', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_webpay', name='webpay_pkey')
    )
    # ### end Alembic commands ###
