"""roles

Revision ID: f2453d31b857
Revises: dcb414a7f89e
Create Date: 2024-05-25 16:35:04.682255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2453d31b857'
down_revision = 'dcb414a7f89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_cliente')
    op.drop_table('rol_vendedor')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint('cliente_rol_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'rol', ['rol_id'], ['id'])

    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sucursal', sa.Integer(), nullable=True))
        batch_op.drop_constraint('vendedor_rol_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'rol', ['rol_id'], ['id'])
        batch_op.create_foreign_key(None, 'sucursal', ['id_sucursal'], ['id_sucursal'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vendedor_rol_id_fkey', 'rol_vendedor', ['rol_id'], ['id'])
        batch_op.drop_column('id_sucursal')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cliente_rol_id_fkey', 'rol_cliente', ['rol_id'], ['id'])
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('rol_vendedor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rol_vendedor_pkey'),
    sa.UniqueConstraint('nombre', name='rol_vendedor_nombre_key')
    )
    op.create_table('rol_cliente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rol_cliente_pkey'),
    sa.UniqueConstraint('nombre', name='rol_cliente_nombre_key')
    )
    # ### end Alembic commands ###
